import type { Metadata } from "next";
import { Geist, Geist_Mono, Josefin_Sans, Atma } from "next/font/google";
import "./globals.css";

const josefin = Josefin_Sans({
  subsets: ['latin'],
  variable: '--font-josefin',
  weight: ['300', '400', '600', '700'],
  display: 'swap',
});

const atma = Atma({
  subsets: ['latin'],
  variable: '--font-atma',
  weight: ['300', '400', '600', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Monitos Shoes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <title>Monitos Shoes</title>
      <body className={
        `${josefin.variable} ${atma.variable}`}>
        {children}
      </body>
    </html>
  );
}
