import type { Metadata } from "next";
import { Atma, Geist, Geist_Mono, Josefin_Sans } from "next/font/google";
import "@/app/globals.css";
import styles from '@styles/dashboard.module.css';
import { Nav } from "@/components/Nav";
import { logoutAction } from "@/api/action";

const josefin = Josefin_Sans({
  subsets: ['latin'],
  variable: '--font-josefin',
  weight: ['300', '400', '600', '700'],
  display: 'swap',
});

const atma = Atma({
  subsets: ['latin'],
  variable: '--font-atma',
  weight: ['300', '400', '600', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
      <div className={`${josefin.variable} ${styles.dashboard} ${atma.variable}`}>
            <header className={styles.header}>
                <h1>ADMINISTRADOR</h1>
                <form action={logoutAction}>
                  <button type="submit" className={styles.logout_button}>
                    CERRAR SESIÓN
                  </button>
                </form>
            </header>
            <Nav />
            <main className={styles.main}>
                {children}
            </main>
    </div>
  );
}
